### ISSUE TITLE
Upcoming breaking changes in elasticsearch gradle plugins for external plugin authors

### ISSUE THREAD

**Issue by breskeby** [spinscale/cookiecutter-elasticsearch-ingest-processor#15]
This is a heads up for you to a change introduced in the elasticsearch gradle plugins that will affect this template. We try to reducing the surface area of those plugins that are only used internally in our own build. Therefore we fixed https://github.com/elastic/elasticsearch/issues/63697 which will result in a break in this template. This change will be part of 7.11. You should be able to fix this by just removing all the task references that you set to "enabled = false". I think.

Thank you,
cheers,
rene

**Comment by spinscale** [comment]
Thx for the heads-up Rene! **Much** appreciated!

**Comment by spinscale** [comment]
Fixed in https://github.com/spinscale/cookiecutter-elasticsearch-ingest-processor/commit/a968569dd8f7e83c3c5ef60e8b7529585cd8477e
