### ISSUE TITLE
debugging my tests

### ISSUE THREAD

**Issue by ruria** [spinscale/cookiecutter-elasticsearch-ingest-processor#8]
Hi, 
I would like to debug my tests, but `gradle test --debug-jvm` doesn´t seem to work. 
I´m pretty new to Gadle, any help will be appreciate.

**Comment by spinscale** [comment]
this is not really a question for this project, as this is about debugging Elasticsearch.

please check the Elasticsearch [TESTING](https://github.com/elastic/elasticsearch/blob/master/TESTING.asciidoc) documentation.

Debugging unit tests can be done within your IDE.
